# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json
%YAML 1.1
---
plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

# I don't write these files, so I don't lint them either
AllCops:
  NewCops: enable
  Exclude:
    - '**/config.ru'
    - '**/db/schema.rb'
    - '**/node_modules/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# Configuration and specs use long blocks as part of their DSL
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - config/environments/*
    - config/routes.rb
    - "**/*_spec.rb"

# I could honestly live without alias
Style/Alias:
  EnforcedStyle: prefer_alias_method

# Prefer the functional "Jim Weirich" style of braces
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# Clear naming and Rspec specifications should be enough
Style/Documentation:
  Enabled: false

# Not sure I have a strong preference here
Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

# tabs vrs spaces for a new generation
Style/StringLiterals:
  Enabled: false

# no strong feelings on this one either
Style/QuotedSymbols:
  Enabled: false

# These feel overkill for arrays of just two elements
Style/SymbolArray:
  MinSize: 3

# Sometimes work with arrays of tuples, this avoid mixed styles for those arrays
Style/WordArray:
  Enabled: true
  MinSize: 3

# Allow leading underscores on memoized variables
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

### Rspec

RSpec/DescribedClass:
  Enabled: false

FactoryBot/SyntaxMethods:
  Enabled: false

### BK specific

Layout/LineLength:
  Max: 160

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 20

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
  Max: 10
