tap "getantibody/tap"
tap "homebrew/bundle"

brew "awscli"
brew "getantibody/tap/antibody"
brew "chruby"
brew "cmake"
brew "dos2unix"
brew "go", args: ["cross-compile-common"]
brew "htop"
brew "node"
brew "reattach-to-user-namespace"
brew "ruby-install"
brew "tmux"
brew "vim", args: ["with-override-system-vi"]
brew "zsh"

cask "1password"
cask "aws-vault"
cask "dropbox"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "slack"
cask "spectacle"
cask "virtualbox"
#cask "virtualbox-extension-pack"
