tap "getantibody/tap"
tap "homebrew/bundle"

cask "1password"
cask "1password-cli"
cask "aws-vault"
cask "dash"
cask "deluge"
cask "dropbox"
cask "flux"
cask "java"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "little-snitch"
cask "openoffice"
cask "sequel-pro"
cask "slack"
cask "spectacle"
cask "steam"
cask "virtualbox"
cask "vlc"

brew "awscli"
brew "getantibody/tap/antibody"
brew "chruby"
brew "cmake"
brew "ctags"
brew "dfu-util" # for configuring my Ergodox keyboard
brew "dos2unix"
brew "fzf"
brew "go", args: ["cross-compile-common"]
brew "heroku"
brew "htop"
brew "hub"
brew "mas"
brew "mono"
brew "mysql"
brew "nvm"
brew "plantuml"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby-install"
brew "speedtest-cli"
brew "the_silver_searcher"
brew "tmux"
brew "todo-txt"
brew "vim", args: ["with-override-system-vi"]
brew "youtube-dl"
brew "zsh"

# 99dev
tap "caskroom/cask"
cask "docker"
cask "vagrant"
cask "virtualbox-extension-pack"
brew "docker-machine-nfs"
brew "oniguruma"
brew "jq"

# Quicklook plugins from https://github.com/sindresorhus/quick-look-plugins
cask "betterzipql"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "webpquicklook"

mas "NordVPN", id: 1116599239
mas "Keynote", id: 409183694
mas "Monodraw", id: 920404675
mas "Numbers", id: 409203825
