shell = "zsh -c '{}'"
default-scheme = "base16-bright"

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = ". %f"
supported-systems = ["base16", "base24"]

[[items]]
name = "base16-vim"
path = "https://github.com/tinted-theming/base16-vim"
themes-dir = "colors"
supported-systems = ["base16"]

[[items]]
name = "tinted-kitty"
path = "https://github.com/tinted-theming/tinted-kitty"
themes-dir = "colors"
hook = "kitty @ set-colors -a -c %f"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-fzf"
name = "tinted-fzf"
themes-dir = "sh"
